Resources:
  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: '.'
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          VERSION: "v1.0.10"
          REGION: "eu-central-1"
          DIST_OUTPUT_BUCKET: "db-serverless-image-handler"
          SOLUTION_NAME: "image-resize-service-eu"
          SOURCE_BUCKETS: "dronebase-production,dronebase-staging,dronebase-uploads-staging,dronebase-uploads-production,dronebase-development"
          TRUNCATE_PATH_PREFIX: "resized_images/"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
